#!/bin/bash
echo "=== XuanJi Technology Website Deployment ==="
echo ""
echo "1. Install dependencies:"
echo "   npm install"
echo ""
echo "2. Start development server:"
echo "   npm start"
echo ""
echo "3. Visit website:"
echo "   Frontend: http://localhost:8000/"
echo "   Admin Panel: http://localhost:8000/admin"
echo ""
echo "4. Default admin credentials:"
echo "   Username: admin"
echo "   Password: admin123"
echo ""
echo "=== Vercel Deployment ==="
echo ""
echo "1. Install Vercel CLI:"
echo "   npm install -g vercel"
echo ""
echo "2. Login to Vercel:"
echo "   vercel login"
echo ""
echo "3. Deploy:"
echo "   vercel --prod"
echo ""
echo "4. Set environment variables in Vercel dashboard:"
echo "   JWT_SECRET=your-secret-key-here"
echo ""
echo "=== Environment Variables ==="
echo "JWT_SECRET - Secret key for JWT tokens (required for production)"
echo ""
echo "=== Notes ==="
echo "- Database is automatically created in database.db"
echo "- Uploads are stored in /uploads directory"
echo "- Admin panel is available at /admin"
