const fs = require('fs');
const path = require('path');

const adminPath = path.join(__dirname, '../admin/index.html');
let content = fs.readFileSync(adminPath, 'utf8');

const oldShowPage = "document.getElementById('dashboard-content').style.display = 'none';\n      document.getElementById('analytics-content').style.display = 'none';\n      document.getElementById('products-content').style.display = 'none';\n      document.getElementById('add-product-content').style.display = 'none';\n      document.getElementById('inquiries-content').style.display = 'none';\n\n      if (page === 'dashboard') {\n        document.getElementById('page-title').textContent = 'Dashboard';\n        document.getElementById('dashboard-content').style.display = 'block';\n        loadStats();\n      } else if (page === 'analytics') {\n        document.getElementById('page-title').textContent = 'Analytics';\n        document.getElementById('analytics-content').style.display = 'block';\n        loadAnalytics();\n      } else if (page === 'products') {\n        document.getElementById('page-title').textContent = 'Products';\n        document.getElementById('products-content').style.display = 'block';\n        loadProducts();\n      } else if (page === 'add-product') {\n        document.getElementById('page-title').textContent = 'Add New Product';\n        document.getElementById('add-product-content').style.display = 'block';\n        document.getElementById('form-industry').value = '';\n        document.getElementById('form-category').innerHTML = '<option value=\"\">Select Category</option>';\n        document.getElementById('product-form').reset();\n      } else if (page === 'inquiries') {\n        document.getElementById('page-title').textContent = 'Customer Inquiries';\n        document.getElementById('inquiries-content').style.display = 'block';\n        loadInquiries();\n      }\n    }";

const newShowPage = "document.getElementById('dashboard-content').style.display = 'none';\n      document.getElementById('analytics-content').style.display = 'none';\n      document.getElementById('products-content').style.display = 'none';\n      document.getElementById('add-product-content').style.display = 'none';\n      document.getElementById('categories-content').style.display = 'none';\n      document.getElementById('add-category-content').style.display = 'none';\n      document.getElementById('inquiries-content').style.display = 'none';\n\n      if (page === 'dashboard') {\n        document.getElementById('page-title').textContent = 'Dashboard';\n        document.getElementById('dashboard-content').style.display = 'block';\n        loadStats();\n      } else if (page === 'analytics') {\n        document.getElementById('page-title').textContent = 'Analytics';\n        document.getElementById('analytics-content').style.display = 'block';\n        loadAnalytics();\n      } else if (page === 'products') {\n        document.getElementById('page-title').textContent = 'Products';\n        document.getElementById('products-content').style.display = 'block';\n        loadProducts();\n      } else if (page === 'add-product') {\n        document.getElementById('page-title').textContent = 'Add New Product';\n        document.getElementById('add-product-content').style.display = 'block';\n        document.getElementById('form-industry').value = '';\n        document.getElementById('form-category').innerHTML = '<option value=\"\">Select Category</option>';\n        document.getElementById('product-form').reset();\n      } else if (page === 'categories') {\n        document.getElementById('page-title').textContent = 'Categories';\n        document.getElementById('categories-content').style.display = 'block';\n        loadCategoriesList();\n      } else if (page === 'add-category') {\n        document.getElementById('page-title').textContent = 'Add New Category';\n        document.getElementById('add-category-content').style.display = 'block';\n        document.getElementById('category-form').reset();\n      } else if (page === 'inquiries') {\n        document.getElementById('page-title').textContent = 'Customer Inquiries';\n        document.getElementById('inquiries-content').style.display = 'block';\n        loadInquiries();\n      }\n    }";

content = content.replace(oldShowPage, newShowPage);
fs.writeFileSync(adminPath, content, 'utf8');
console.log('showPage updated');
