const fs = require('fs');
const path = require('path');

const adminPath = path.join(__dirname, '../admin/index.html');
let content = fs.readFileSync(adminPath, 'utf8');

const searchStr = "function logout() {\n      token = null;\n      localStorage.removeItem('token');\n      document.getElementById('dashboard').style.display = 'none';\n      document.getElementById('login-page').style.display = 'flex';\n    }";

const replaceStr = "function logout() {\n      token = null;\n      localStorage.removeItem('token');\n      document.getElementById('dashboard').style.display = 'none';\n      document.getElementById('login-page').style.display = 'flex';\n    }\n\n    async function loadCategoriesList() {\n      const industry = document.getElementById('category-filter-industry')?.value;\n      const url = industry ? `/api/categories?industry=${industry}` : '/api/categories';\n      const response = await fetch(url);\n      const data = await response.json();\n      \n      if (data.success) {\n        const tbody = document.getElementById('categories-table-body');\n        tbody.innerHTML = data.data.map(c => `\n          <tr>\n            <td>${c.id}</td>\n            <td>${c.name}</td>\n            <td>${c.industry.charAt(0).toUpperCase() + c.industry.slice(1)}</td>\n            <td>\n              <button class=\"btn btn-secondary\" onclick=\"editCategory(${c.id})\" style=\"padding: 5px 10px; font-size: 0.8rem;\">Edit</button>\n              <button class=\"btn btn-danger\" onclick=\"deleteCategory(${c.id})\" style=\"padding: 5px 10px; font-size: 0.8rem;\">Delete</button>\n            </td>\n          </tr>\n        `).join('');\n      }\n    }\n\n    function showAddCategory() {\n      showPage('add-category');\n    }\n\n    async function deleteCategory(id) {\n      if (!confirm('Are you sure you want to delete this category?')) return;\n      const response = await fetch(`/api/categories/${id}`, {\n        method: 'DELETE',\n        headers: { Authorization: `Bearer ${token}` }\n      });\n      const data = await response.json();\n      if (data.success) {\n        alert('Category deleted successfully');\n        loadCategoriesList();\n      } else {\n        alert(data.error);\n      }\n    }\n\n    async function editCategory(id) {\n      const response = await fetch(`/api/categories/${id}`);\n      const data = await response.json();\n      if (data.success) {\n        const cat = data.data;\n        const form = document.getElementById('category-form');\n        form.name.value = cat.name;\n        form.industry.value = cat.industry;\n        form.dataset.id = id;\n        document.getElementById('page-title').textContent = 'Edit Category';\n        document.getElementById('add-category-content').style.display = 'block';\n      }\n    }";

content = content.replace(searchStr, replaceStr);
fs.writeFileSync(adminPath, content, 'utf8');
console.log('Category functions added');
